version: "3"
services:
  frontend:
    container_name: frontend
    build: 
      context: frontend/.
      dockerfile: Dockerfile
    ports: 
      - 80:80
    environment: 
      ENV_NAME: test
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: backend/.
      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
    environment:
      ENV_NAME: test
    restart: unless-stopped

  database:
    image: mongo:5.0.6
    container_name: database
#    ports:
#      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      ENV_NAME: test
    restart: unless-stopped
