version: "3"
services:

  frontend:
    container_name: frontend
    build: 
      context: frontend/.
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports: 
      - 80:80
    environment: 
      ENV_NAME: test
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: backend/.
      dockerfile: Dockerfile
    depends_on:
      - database
#    ports:
#      - 8080:8080
    environment:
      ENV_NAME: test
    restart: unless-stopped

  database:
    container_name: database
    build:
      context: database/.
      dockerfile: Dockerfile
#    ports:
#      - 27017:27017
    volumes:
      - ./database/data:/data/db
      - ./database/backup:/backup
    environment:
      ENV_NAME: test
      ENV_USER_EXPIRE_AFTER_SECONDS: ${USER_EXPIRE_AFTER_SECONDS:-86400}
    restart: unless-stopped
